### ISSUE TITLE
Light theme for xManager

### ISSUE THREAD

**Issue by ghost** [Team-xManager/xManager#214]
### Description of the new feature / enhancement

I'm not sure if this possible, If it can change between dark and light depending on system theme it would be cool.
Otherwise just light theme should be fine

**Comment by Black-StellarSpectrum** [comment]
Is light theme for Spotify not possible?

**Comment by doughnut9** [comment]
> Is light theme for Spotify not possible?

What kind of demon wants Spotify light mode?

**Comment by xC3FFF0E** [comment]
Light Themes has been added on the latest version (5.5): https://github.com/Team-xManager/xManager/releases/tag/5.5
