### ISSUE TITLE
Download speeds are really slow 

### ISSUE THREAD

**Issue by hax4dazy** [Team-xManager/xManager#314]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: OnePlus 9
- Android Version: Android 12
- ROM Version: Stock
- xManager Version: 4.8
```

### 📝 Description

1. Open the app
2. Download one of the distributions in the app
3. Observe it downloading at 140kbps

**Comment by xC3FFF0E** [comment]
Depending on your ISP. We're using a premium sub dropbox to host our files and it works fine in some cases.

**Comment by hax4dazy** [comment]
I tried with VPN (windscribe) without VPN and on a mobile network. None of the above gave me good speeds. Is there maybe a chance these can be hosted using GH pages or something? That would work a lot better

**Comment by xC3FFF0E** [comment]
> Is there maybe a chance these can be hosted using GH pages or something? That would work a lot better

Not possible at the moment.
