### ISSUE TITLE
Client for linux

### ISSUE THREAD

**Issue by mohammadRezaeian** [Team-xManager/xManager#321]
### Description of the new feature / enhancement

hi thanks for create this application 
this application create a best times for me
please if it possible create a version of for linux
again thanks.

**Comment by nsde** [comment]
You can use BlockTheSpot instead. Works fine

**Comment by DarkCrypt** [comment]
Or...

You can use an Android emulator for Linux and run all apps and games besides xManager.

Or better yet...

You can use VirtualBox and run any operating systems you want.
