### ISSUE TITLE
Is XManager open source?

### ISSUE THREAD

**Issue by ghost** [Team-xManager/xManager#324]
Hi.~ I was wondering whether this app is open source and how can I trust it?~

So I see that there is some source; is it 100% open source?

I believe I read something which implied that this project is not.

**Comment by bookarticle** [comment]
And can I trust the closed source patches? Why are they close sourced?

**Comment by bookarticle** [comment]
I don't get it; why not have your own open source patches and apply them to an apk?

**Comment by xC3FFF0E** [comment]
Check each individual file in this repo.

**VT Analysis:** [Click Here](https://www.virustotal.com/gui/file/994ea1d7b7cea1ab7f9ffb18b24ea8f58cd9d511ac8c5dc967d47207c55fa891/detection)
