### ISSUE TITLE
Android Auto integration fix

### ISSUE THREAD

**Issue by WueXiang** [Team-xManager/xManager#325]
This Spotify doesn't work with Android Auto for now, not detected in Android Auto.

Any plan to fix this? Or is there any reason making it impossible? 

This issue serve for discussion purpose.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by GitHub0901** [comment]
Hi! You must  enable developer mode in AA (https://developer.android.com/training/cars/testing?hl=en)
Then I leave a tip: if you use your voice to select music, don't associate AA with xManager app. If you do, you will receive a message like this "You must select Premium plan to choice your songs", but if you don't associate, xManager select songs and the voice will say something like "The song that you ask is playing at xManager" :-)
