### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by p6n7l** [Team-xManager/xManager#331]
Not sure if possible and it s not a necessity, but could downloading songs be implemented using the spotdl library?

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
