### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by LazyCoder26** [Team-xManager/xManager#334]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Nothing Phone (1)
- Android Version: 13
- ROM Version: unknown
- xManager Version: 4.9
```

### 📝 Description

1. Download is not working

I recently purchased nothing phone 1
When I want to download the music is not working instead when I click on download it takes me back to home screen

But in my old device which is honor 7x it starts download immediately , version is Android 9
xManager version 4.9

Can you know what is causing the issue
And other things suddenly I can log in via my phone number, previously I can 
Does Spotify banned by phone number?

### 📸 Screenshots

![Screenshot_20230607-234800](https://github.com/Team-xManager/xManager/assets/77568653/1bd626de-4c99-4b9e-b9d2-69452a2d6f22)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
