### ISSUE TITLE
Lyrics not showing on mobile

### ISSUE THREAD

**Issue by Y0b0** [Team-xManager/xManager#336]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  samsung a32
- Android Version:  android 13
- ROM Version:  stock
- xManager Version:  4.9
```

### 📝 Description

1.
2.
3.
...
When i open a song i can't see the lyrics where it normally is I've tried logging in again or even clearing cache but it still doesn't show lyrics...
I know not all songs have the lyrics but I've tried opening ones that had them before but they also don't show...
Please assist.thank you

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
