### ISSUE TITLE
Add option to unlock Very High quality playback settings

### ISSUE THREAD

**Issue by rajpreet903** [Team-xManager/xManager#338]
### Description of the new feature / enhancement

- Adding option to unlock very High quality playback make one to access 320kbps audio quality, which improve user experience.

**Comment by xC3FFF0E** [comment]
Server-side feature, so no.

Also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
