### ISSUE TITLE
Hook share button

### ISSUE THREAD

**Issue by Radical4ever** [Team-xManager/xManager#339]
### Description of the new feature / enhancement

- 1 make the share button hook to an external downloader app (copies the song's link)
- 2 you could change this option from the app itself or pre configure it on xmanager
- 3 enjoy downloading songs!

This is something that revanced team made with youtube music and it works flawlessly

**Comment by xC3FFF0E** [comment]
Unfortunately, we don't have any plans adding any sort of "downloading" options within the manager app nor to the patched applications. We will not risk our user's accounts getting suspended or ban. So no, sorry.
