### ISSUE TITLE
Video podcasts while in a car

### ISSUE THREAD

**Issue by kkellogg378** [Team-xManager/xManager#341]
### Description of the new feature / enhancement

- 1 spotify disables video podcasts while connected to car/car thing, and after work I like to sit in my car and listen to Distractible. But spotify won't let me watch the video while I'm connected to my car. Just asking for a fix
- 2
- 3

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
