### ISSUE TITLE
Unable to log in on spotify 

### ISSUE THREAD

**Issue by asds-mission** [Team-xManager/xManager#342]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  redmi note 9
- Android Version:  Android 12
- ROM Version:  
- xManager Version:  4.9
```

### 📝 Description

1.Spotify doesn't log in using email and password.
2.Spotify cannot create new account using any method.
3.tge message " Something went wrong. Try again" is displayed in any login/signup case
...

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
