### ISSUE TITLE
Ads played when casting to Google home mini speaker 

### ISSUE THREAD

**Issue by SpideySparks** [Team-xManager/xManager#343]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  OPPO Reno 8T 5G
- Android Version:  13
- ROM Version:  Color OS 13
- xManager Version:  4.9
```

### 📝 Description

1.Open Spotify
2.Play any track
3.change the audio output to connected Google Speaker/Chromecast 
...

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
