### ISSUE TITLE
Unable to play any song after installing Wave

### ISSUE THREAD

**Issue by tempaccount666666** [Team-xManager/xManager#344]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  s23 ultra
- Android Version:  13
- ROM Version:  oneui 5.1
- xManager Version:  5.0
```

### 📝 Description

1. Download Wave (the latest)
2. Try to play s song
3. Notice a popup saying youre not allowed to play a song without a subscription

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
