### ISSUE TITLE
Tidal download problem

### ISSUE THREAD

**Issue by fahdokun** [Team-xManager/xManager#347]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Huawei mate 10 pro
- Android Version: Android 12 
- ROM Version:  exclusive
- xManager Version:  5.0
```

### 📝 Description

I did every step in the tele instructions, but i cant download any songs. 
It keeps saying not enough storage, but I got 2gb storage left, is it not enough? 

### 📸 Screenshots

![Screenshot_20230721_195146](https://github.com/Team-xManager/xManager/assets/140193823/e7491ce3-faec-44a3-9fc5-b4a584c2dd82)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
