### ISSUE TITLE
Spotify on Android Auto

### ISSUE THREAD

**Issue by Raulking898** [Team-xManager/xManager#348]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Pixel 7 
- Android Version: Android 14 beta 4.1 
- ROM Version: stock
- xManager Version: The newest version
```

### 📝 Description

I can't use spotify on android auto. It doesn't work

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by GitHub0901** [comment]
Hi! You must  enable developer mode in AA (https://developer.android.com/training/cars/testing?hl=en)
Then I leave a tip: if you use your voice to select music, don't associate AA with xManager app. If you do, you will receive a message like this "You must select Premium plan to choice your songs", but if you don't associate, xManager select songs and the voice will say something like "The song that you ask is playing at xManager" :-)
