### ISSUE TITLE
Spotify not patchable / can't login with any version of spotify patch nor xmanager

### ISSUE THREAD

**Issue by Geistica** [Team-xManager/xManager#349]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Nothing 2
- Android Version:  Android 13
- ROM Version:  stock
- xManager Version:  5.0
```

### 📝 Description

1. Download xmanager
2. Download Spotify
3. Install patch
4. trying to log in with google "Something went wrong"

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
