### ISSUE TITLE
Option to hide sections

### ISSUE THREAD

**Issue by iloveviolin** [Team-xManager/xManager#351]
### Description of the new feature / enhancement

- 1 If I only have Exp Amoled installed, it would be handy if we could hide other sections
- 2 When only 1 item is installed then only Exp Amoled and Changelog sections would be visible
- 3 This would make refreshing a lot quicker

**Comment by xC3FFF0E** [comment]
Hi there. This feature is now added on the latest version of the manager app. Kindly check it here: https://github.com/Team-xManager/xManager/releases/tag/5.1

Let me know if you have any further questions. Thanks!
