### ISSUE TITLE
There was a problem parsing the package

### ISSUE THREAD

**Issue by kenjibailly** [Team-xManager/xManager#353]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Redmi Note 10 pro
- Android Version:  13
- ROM Version:  PixelOS
- xManager Version:  4.9, 5.0
```

### 📝 Description

1. Uninstall Spotify
2. Download patched
3. Install patched
4. Get error

Tested on 5.0 and 4.9, tried older release, but same thing happens.

...

### 📸 Screenshots

![Screenshot_20230805-121425_Package_installer](https://github.com/Team-xManager/xManager/assets/9883910/15a4e7e0-5f9a-40c8-bc37-a966241b6878)

**Comment by MartynasSapoka** [comment]
I have the same issue. As a workaround, when the apk is downloading, you can click "alternate mirror" button. That one installs without a hitch.

There must be something wrong with the main download as the apk is only ~60kb in size

**Comment by xC3FFF0E** [comment]
All links are now partially up. Try to download it again. Let me know if the issue persists. Thanks!

**Comment by akashpal-21** [comment]
Issue persists, cannot download anything, file downloaded is 60kb, throws parsing error, dont know what is happening

**Comment by DarkCrypt** [comment]
I prefer using the "MIRROR LINK" because the default download never works correctly for me.

Hit "REFETCH AND REBOOT" at the bottom left in xManager settings and then retry downloading your patch.

This usually fixes any issues for me.

**Comment by xC3FFF0E** [comment]
We partially fixed some of the links. Try to redownload again. If the issue persists, use the mirror link else visit one of our support channels for further assistance. Thanks!

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by vvirtues** [comment]
Usually it always downloads the file, but after signing/finalizing etc. I get this error. Installing through the mirror link is flawless, except that when I try to auto update through the app it tells me that xmanager did not install it

**Comment by rafrifray** [comment]
I can download it but when needed to install it parsing error pop out

**Comment by DarkCrypt** [comment]
> I can download it but when needed to install it parsing error pop out

Use the mirror link.

**Comment by flatline-studios** [comment]
> > I can download it but when needed to install it parsing error pop out
> 
> Use the mirror link.

How?

**Comment by vvirtues** [comment]
> > > I can download it but when needed to install it parsing error pop out
> > 
> > 
> > Use the mirror link.
> 
> How?

While it's downloading, youll see a "mirror link" button
Click on it and it should open a mediafire page
Download from there and install yourself

**Comment by FyhexCode** [comment]
> > > > I can download it but when needed to install it parsing error pop out
> > > 
> > > 
> > > Use the mirror link.
> > 
> > 
> > How?
> 
> While it's downloading, youll see a "mirror link" button Click on it and it should open a mediafire page Download from there and install yourself

I can't find the mirror link download

**Comment by vvirtues** [comment]
While downloading, the button is right there
https://github.com/Team-xManager/xManager/assets/81705406/b2571b03-ee80-44b2-af43-6b9550ccd7de

**Comment by fldc** [comment]
> While downloading, the button is right there
> 
>  screen-20231004-104006.mp4

This should be an option, the download is like half a second, I haven't been able to push this button.

**Comment by vvirtues** [comment]
> > While downloading, the button is right there
> > screen-20231004-104006.mp4
> 
> This should be an option, the download is like half a second, I haven't been able to push this button.

Be thankful your wifi is that fast 😭

**Comment by kenjibailly** [comment]
When it asks

Existing Patched
An existing patched has been detected at the external directory. What action would you like to do?

Instead of click install, I clicked ignore, then download and install it.
That somehow worked for me now.
