### ISSUE TITLE
[Question] Does spotify can ban your account?

### ISSUE THREAD

**Issue by iMaciaP** [Team-xManager/xManager#354]
### Description of the new feature / enhancement

I've been using this for a while and haven't had any problem, but just yesterday i was helping a friend of mine to have xmanager also and everywhere i had spotify it closed my session and can't login back.

Any help or idea of how to manage this?

Thank you.

**Comment by iMaciaP** [comment]
Don't know why but with facebook login i can login finally, sorry for the issue I panicked a bit

**Comment by DarkCrypt** [comment]
Weird. I tried to test this by logging out and closing the app. I reopened the app and logged in with email/password without issue.

Can you login to Spotify in your browser?

**Comment by sleepingiv** [comment]
Yes , but it says playback suspended for blocking ads.

**Comment by DarkCrypt** [comment]
It says the same thing for me using Brave but works fine using 1DM.
