### ISSUE TITLE
Installation(patched Spotify) failed: verification failed install not allowed

### ISSUE THREAD

**Issue by Qattos** [Team-xManager/xManager#356]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A52s 5G
- Android Version:  13
- ROM Version:  LineageOS 20
- xManager Version:  5.0
```

### 📝 Description

1. Downloaded AMOLED patched apk through xManager
2. Clicked to install it
3. Fail with message saying: verification failure, installation not allowed.

### 📸 Screenshots

![Screenshot_20230811-185523_App Manager](https://github.com/Team-xManager/xManager/assets/56252966/953bd4ac-cd24-4575-9ff9-4c11fb8dfaad)

**Comment by xC3FFF0E** [comment]
Redownload again else visit one of our support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
