### ISSUE TITLE
Create a desktop (Linux, Windows, Mac) version of xManager

### ISSUE THREAD

**Issue by ayntk-ai** [Team-xManager/xManager#357]
### Description of the new feature / enhancement

I mostly listen to music on Spotify on my laptop or PC, so it would be great to be able to use these patched apps on the desktop. If this is already available, how can I do this? if possible without the need for any android mod on my pc.

**Comment by xC3FFF0E** [comment]
Use SpotX for Windows and MacOS.

**Comment by G0V1NDS** [comment]
https://github.com/amd64fox/SpotX/issues/358
