### ISSUE TITLE
Add offline support for Spotify

### ISSUE THREAD

**Issue by ayntk-ai** [Team-xManager/xManager#358]
### Description of the new feature / enhancement

Add the option to download the playlist to Spotify so I can listen to it offline.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by Astro4l** [comment]
How are we to seek support on Telegram if the admins have restricted sending messages?
