### ISSUE TITLE
is this avaiable on ios?

### ISSUE THREAD

**Issue by athallahgd** [Team-xManager/xManager#359]
### Description of the new feature / enhancement

- 1
- 2
- 3

**Comment by xC3FFF0E** [comment]
At the moment, no. Try using Spotilife.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
