### ISSUE TITLE
Latest patch ad glitch 

### ISSUE THREAD

**Issue by Bubbadubscrub** [Team-xManager/xManager#360]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: OnePlus 11 5g
- Android Version:  Android 13
- ROM Version:  stock
- xManager Version:  5.0
```

### 📝 Description

When I went to download wave patch latest release, it pops an ad up. After watching the ad, i hit the X and it goes back without downloading

**Comment by xC3FFF0E** [comment]
All links are partially up so you will need to try again else visit one of our support channels for further assistance. Thanks!

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by ZenoBell** [comment]
Tey to switch off ad blockers etc. I had same issue as im running pihole in the local network. Temporary disabling it or switching your phone to mobile data should do the trick.
