### ISSUE TITLE
Spotify has login problem

### ISSUE THREAD

**Issue by alamf332** [Team-xManager/xManager#362]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  iqoo neo 7
- Android Version:  13
- ROM Version:  MOLY.NR16.R1.MP3.TC19.PR1.SP.V1.P142
- xManager Version:  5.0
```

### 📝 Description

1. Spotify has login problem. 
2. After entering the right email-password combination still it is showing that it is wrong. 
3. I tried uninstall-install but it is same. 
4. Can't login after resetting the password. 
5. It is not even sending the reset password mail. 

### 📸 Screenshots

1. Spotify has login problem. 
2. After entering the right email-password combination still it is showing that it is wrong. 
3. I tried uninstall-install but it is same. 
4. Can't login after resetting the password. 
5. It is not even sending the reset password mail.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
