### ISSUE TITLE
Spotify Canvas doesn't work

### ISSUE THREAD

**Issue by dankent4321** [Team-xManager/xManager#364]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Android Version:  Android 7.1.2
- xManager Version:  5.0
- Spotify Version:  8.8.56.538
```

### 📝 Description

Hello, why is Spotify Canvas not working?

Spotify Canvas is available in my country. "Save Data" option is disabled.

![Screenshot_2023-08-20-18-55-47-258_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/5d48972c-54d2-498e-87f0-1fb18175ad0d)

The option does work on another Spotify app that I used:

![Screenshot_2023-08-20-17-58-14-863_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/4d60f278-90a5-41f8-be05-17b78aa41216)

But not on Spotify from xManager:

![Screenshot_2023-08-20-18-14-17-023_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/e01ce05d-1a55-4c49-955c-cf5e7a5188b4)

What could I do? Thank you.

**Comment by DarkCrypt** [comment]
Working for me. Do you have the Canvas option toggled on in Settings? Based on your above screenshot, scroll down a little more.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by dankent4321** [comment]
> Working for me. Do you have the Canvas option toggled on in Settings? Based on your above screenshot, scroll down a little more.

I don't have the Canvas option in settings. I already restarted the app several times and cleared the cache. What could I do? Thank you.

![Screenshot_2023-08-21-11-51-22-034_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/a96a651d-2043-4eaf-88fa-b7d6dca7344c)
![Screenshot_2023-08-21-11-52-08-672_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/751163e0-c8aa-4628-82de-c2abd0173ce3)
![Screenshot_2023-08-21-11-52-38-939_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/88e1fb19-35ea-43bd-815e-932f8e56d78f)
![Screenshot_2023-08-21-11-53-07-735_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/e22cccf1-666c-4699-8608-12e9ec8945fd)
![Screenshot_2023-08-21-11-53-29-414_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/73786064-26ee-46e6-8116-5e395e2e9333)
![Screenshot_2023-08-21-11-54-21-373_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/a158437c-b400-466c-a942-2bac3418be03)
![Screenshot_2023-08-21-11-56-01-657_com spotify music](https://github.com/Team-xManager/xManager/assets/142740770/751f66ef-e8ab-4d63-b2ce-7da35fb3d3bf)
