### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by SsubezZ** [Team-xManager/xManager#365]
### Description of the new feature / enhancement

Adding adaptive icons would be great.

**Comment by xC3FFF0E** [comment]
Already implemented since v3.6. Check it here: https://github.com/Team-xManager/xManager/releases/tag/3.6

**Comment by SsubezZ** [comment]
Doesnt work for me tho. 
![Screenshot_20230823-171547_Trebuchet](https://github.com/Team-xManager/xManager/assets/119054422/58a98fba-4950-4d8b-b8ac-acc27d9dcc39)
