### ISSUE TITLE
Wave mod failed

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [Team-xManager/xManager#366]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung S22 Ultra NON ROOT
- Android Version:  13
- ROM Version:  stock
- xManager Version:  latest
```

### 📝 Description

1. I install the mod and register in tidal, one Video works and the He said that i doesnt have a Premium Account, I cannot Stream anything. I reinstall via xManager but doesnt work
2.
3.
...

**Comment by IT-EXPRESS-Munich** [comment]
> Sign up an account using VPN with USA location.

Only sign up? Or using after too with vpn

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
