### ISSUE TITLE
i can't install

### ISSUE THREAD

**Issue by EchoVrHacks** [Team-xManager/xManager#368]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Oneplus 9
- Android Version: 13
- ROM Version: stock
- xManager Version:  5.0
```

### 📝 Description

1. install x manager
2.  try to download any version
3. stays stuck at 91%
4. ?????
5. Profit
...
like nothing works anymore (also not the installer)

**Comment by xC3FFF0E** [comment]
Use the mirror link beside the download button.

**Comment by EchoVrHacks** [comment]
And how do I download the Spotify wave version? 
When I press the mirror button I only come to a tidal APK is that on purpose

**Comment by DarkCrypt** [comment]
I recommend to always use the mirror link. Experiment for yourself.

Tidal = Wave, make sense?

**Comment by EchoVrHacks** [comment]
> I recommend to always use the mirror link. Experiment for yourself.
> 
> Tidal = Wave, make sense?

I thought wave was just the classic x manager Spotify with a download option?

Wait so how do I use that cracked tidal? I read something about needing to connect to a us server with a von because it's only free there 
Can you explain a bit

**Comment by DarkCrypt** [comment]
> Wait so how do I use that cracked tidal? I read something about needing to connect to a us server with a von because it's only free there
Can you explain a bit

I'm not real sure. I've never used Tidal or the Wave version. I only use the Amoled version.

Sounds like what you read is correct if you're not from the US. Check out this [Reddit thread](https://www.reddit.com/r/xManagerApp/comments/150gwdu/question_what_is_wave_patched/) and read through every comment.

**Comment by xC3FFF0E** [comment]
For further information about wave, you can visit one of our support channel for futher assistance.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
