### ISSUE TITLE
The Spotify provided by xManager is no longer working and it's completely impossible to log in. 

### ISSUE THREAD

**Issue by Subtly7360** [Team-xManager/xManager#369]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  OnePlus 9
- Android Version:  Android 13
- ROM Version:  LineageOS 20-20230827-NIGHTLY-lemonade
- xManager Version:  v5.0
- STOCK PATCHED VERSION & AMOLED PATCHED:8.8.56.538
- LITE PATCHED:1.9.0.43809
```

### 📝 Description

The Spotify provided by xManager is no longer working and it's completely impossible to log in. 
In the Lite version, after logging in for the first time and then exiting the application, you need to re-enter your username and password to log back into your Spotify account when you open the app again. However, subsequent login attempts keep failing. 

Therefore, all the apps provided by xManager have become ineffective.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
