### ISSUE TITLE
Cast volume controls not working on Android 12

### ISSUE THREAD

**Issue by GitHubIL** [Team-xManager/xManager#370]
### Description of the new feature / enhancement

I would be happy if you could add a bug fix in Android 12, for cast volume controls, as explained [here](https://www.esper.io/blog/android-12-cast-volume-changes-explained):

> Just as Google disabled this behavior via RRO, so too can savvy users reenable this behavior with an RRO of their own. Simply create a RRO with [a higher priority](https://source.android.com/devices/architecture/rros#static-rros) than the PixelConfigOverlayCommon RRO and the config_volumeAdjustmentForRemoteGroupSessions flag set to true. Installing this RRO will require superuser access, however, as Android [does not allow installing](https://www.xda-developers.com/android-p-blocks-custom-overlays-substratum-themes/) RROs that aren’t signed with the platform certificate.

This bug was fixed in Android 12.1, but there are many devices (such as Galaxy s10) that did not receive this update.

https://9to5google.com/2021/11/30/android-12-chromecast-volume-rocker-legal-issue/

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
