### ISSUE TITLE
Andoid Auto users tip

### ISSUE THREAD

**Issue by GitHub0901** [Team-xManager/xManager#372]
### Description of the new feature / enhancement

Hi! I have some suggestion to Android Auto users.

You must  enable developer mode in AA [https://developer.android.com/training/cars/testing?hl=en](url)
Then I leave a tip: if you use your voice to select music, don't associate AA with xManager app. If you do, you will receive a message like this "You must select Premium plan to choice your songs", but if you don't associate, xManager select songs and the voice will say something like "The song that you ask is playing at xManager" :-)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
