### ISSUE TITLE
First reported Tidal issue - muted?

### ISSUE THREAD

**Issue by KyleSanderson** [Team-xManager/xManager#374]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
so, I first reported this on Discord, and some clown insisted there was no problem then killed the chat after a ton of proof.
```

### 📝 Description

Can the SnR please be raised in Discord.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by KyleSanderson** [comment]
This is specifically around Discord. Paradox is a cancer to your community.
