### ISSUE TITLE
I no longer can set the song to play on loop and the premium tab down at the bottom still appears it does nothing when clicked on tho

### ISSUE THREAD

**Issue by LS771** [Team-xManager/xManager#375]
@![Screenshot_2023-09-10-16-45-38-75_0438eb925998df20b3482ec25499d226.jpg](https://github.com/Team-xManager/xManager/assets/79064234/80449ba4-9a59-43b1-847b-659f78df7a7a)

Example 1

![Screenshot_2023-09-10-16-46-09-20_0438eb925998df20b3482ec25499d226.jpg](https://github.com/Team-xManager/xManager/assets/79064234/56bf3c11-6afc-4691-8306-e63a5f77f31d)

Example 2

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
