### ISSUE TITLE
Add Smart Shuffle

### ISSUE THREAD

**Issue by RiuKy** [Team-xManager/xManager#379]
### Description of the new feature / enhancement

We once had the enhance button with old cracked version but it got replaced with smart shuffle, which is now a premium feature. I don't really want to stick for too long to a really old version so I was guessing if you could add smart shuffle? 

More infos here: https://support.spotify.com/article/shuffle-play/

### 📸 Screenshots

![image](https://github.com/Team-xManager/xManager/assets/119540878/64e38ec4-06fb-4430-921d-8792be36e82e)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
