### ISSUE TITLE
(" There was a problem parsing the package" ) First time using xManager

### ISSUE THREAD

**Issue by GothBoiDamingeR** [Team-xManager/xManager#380]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung galaxy A52 s 5G 
- Android Version:  13
- ROM Version:  stock
- xManager Version:  v5.0
```

### 📝 Description

1.Fresh installed Xmanager from official website
2.Open and select a version (Amoled patched-Latest release)
3. click download and when installing i get a error saying (" There was a problem parsing the package ")

### 📸 Screenshots

![image](https://github.com/Team-xManager/xManager/assets/144977025/f2179d87-7a56-4e55-b9d8-ce57b2f86b66)

**Comment by firmansyahadi94816** [comment]
Same issue, the file size seems to be less than 1 MB.

**Comment by kushal-droid** [comment]
![Screenshot_20231004_095226](https://github.com/Team-xManager/xManager/assets/59605316/d9f49b29-9eaa-4d68-b2fc-602bca1f66da)



Android-13

**Comment by chickendrop89** [comment]
I am also having this problem, using mirror link doesn't work either though

**Comment by xC3FFF0E** [comment]
Duplicate. Check: https://github.com/Team-xManager/xManager/issues/353#issuecomment-1747222852

Closing.
