### ISSUE TITLE
Android Auto Implementation

### ISSUE THREAD

**Issue by Namya-Shah** [Team-xManager/xManager#382]
It doesn't show in Android Auto. If it is missing then you should add it as a feature very helpful. If it is already added then any workaround?

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
