### ISSUE TITLE
There is a problem while parsing the package 

### ISSUE THREAD

**Issue by Babairock22** [Team-xManager/xManager#384]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: POCO F4 
- Android Version:  13
- ROM Version:  MIUI 14 stock
- xManager Version:  5.0 LATEST
```

### 📝 Description

1. I have opened the app.
2. Downloaded the stock patch.
3. At the time of installation it's showing there's a problem while parsing the package.
...

### 📸 Screenshots

![Screenshot_2023-10-06-00-43-21-569_com google android packageinstaller](https://github.com/Team-xManager/xManager/assets/72491255/86c5b2ab-a631-4e22-9273-54b8a7e1dcf4)

**Comment by xC3FFF0E** [comment]
Duplicate. Check: https://github.com/Team-xManager/xManager/issues/353#issuecomment-1747222852

Closing.
