### ISSUE TITLE
My account was suspended by Spotify 

### ISSUE THREAD

**Issue by kokoharioko** [Team-xManager/xManager#385]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Realme 5 Pro
- Android Version:  11
- ROM Version:  latest patch
- xManager Version:  latest
```

### 📝 Description

1. Cant log in
2. Account got suspended
3.
...

### 📸 Screenshots

![Screenshot_2023-10-06-09-56-00-68_680d03679600f7af0b4c700c6b270fe7](https://github.com/Team-xManager/xManager/assets/44386138/63216390-1f65-4ec6-a14a-62bfe81c3184)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
