### ISSUE TITLE
WHY ARE THE APKs BEING FLAGGED FOR VIRUSES??

### ISSUE THREAD

**Issue by Astro4l** [Team-xManager/xManager#386]
Why is one of the APKs flagged by virustotal to be a malware? This has only started happening recently, even Google play protect now flags it as spyware!

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
