### ISSUE TITLE
Error while parsing package

### ISSUE THREAD

**Issue by OrianLena** [Team-xManager/xManager#387]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: OnePlus 8t
- Android Version:  Android 13
- ROM Version:  Nameless-AOSP | Android 13
- xManager Version:  xmanager V5.0
Why can't I install spotify. please help me
```

### 📝 Description

1.can't I install spotify
2.
3.
...

### 📸 Screenshots

![A62E580C6F67170766641DA2427A5DBC](https://github.com/Team-xManager/xManager/assets/114657403/bc17e3d9-f754-4047-bb14-fd738e8fdc44)

**Comment by NeuroCPP** [comment]
The file that is getting downloaded is 75 kb

**Comment by WillD7545** [comment]
![Screenshot_20231008-064855.png](https://github.com/Team-xManager/xManager/assets/9771582/5ef0ca78-ceab-475a-8700-a06e6d4f0da1)

Same

**Comment by Tenclea** [comment]
The file is not even an APK file. If you open it in a browser as HTML, you can see that it is due to a dead Dropbox link. The team's account probably got termed for some reason?

![Screenshot_20231008](https://github.com/Team-xManager/xManager/assets/62174952/1204aa09-0c31-4bd2-8ae7-460e0b893e32)

**Comment by Tenclea** [comment]
If you click the "Mirror Link" button that pops up very briefly when downloading, it will take you to an alternative, working link page :)

**Comment by xC3FFF0E** [comment]
Duplicate. Check: https://github.com/Team-xManager/xManager/issues/353#issuecomment-1747222852

Closing.
