### ISSUE TITLE
allow hiding of patch types

### ISSUE THREAD

**Issue by Aracnoss** [Team-xManager/xManager#388]
### Description of the new feature / enhancement

As title says, selectively allow hiding of patch types, such as amoled or waved patch in the xManager UI.

This is definitely a low priority quality of life change, but I think this would help decluttering the UI.

Plus if more patch types are introduced, like the Waved patch, it could be inverted to default hide, then in some cases, allow selectively showing them instead.

**Comment by xC3FFF0E** [comment]
Hi there. This feature is now added on the latest version of the manager app. Kindly check it here: https://github.com/Team-xManager/xManager/releases/tag/5.1

Let me know if you have any further questions. Thanks!

**Comment by Aracnoss** [comment]
Just updated the app and noticed! Thanks @xC3FFF0E, great work as always.
