### ISSUE TITLE
Bug Report - Volume Control Issue on Spotify Mobile App

### ISSUE THREAD

**Issue by gejiimayu** [Team-xManager/xManager#389]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [ ] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Honor X8 TFY-LX1
- Android Version:  13
- ROM Version:  stock
- xManager Version: 4.9
```

### 📝 Description

1.Title: Bug Report - Volume Control Issue on Spotify Mobile App

Bug Description:

Issue Summary:
When adjusting the volume on the Spotify mobile app, the connected television, which is controlled through the phone, does not respond as expected.

### 📸 Screenshots

![Изображение WhatsApp 2023-10-16 в 17 34 01_846c521d](https://github.com/Team-xManager/xManager/assets/148064383/b35fa8a6-507b-4ee6-a581-0f3651ff0ede)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
