### ISSUE TITLE
Spotify is showing up in Play Store as Installed and Update Available

### ISSUE THREAD

**Issue by OldBuffGuy** [Team-xManager/xManager#392]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Pixel 6 Pro
- Android Version:  Android 14
- ROM Version:  stock 8.8.74.652
- xManager Version:  5.0
```

### 📝 Description

1. Open Play Store
2. Enter "Spotify" in Search Bar and select Spotify in apps list
3. See two options on Spotify App Store page: Uninstall and Update
...
It never showed up as Installed or that Updates are Available in the Play Store with past versions.

### 📸 Screenshots

![Screenshot_20231025-223214](https://github.com/Team-xManager/xManager/assets/1783037/8d9a7ad2-297c-404b-884f-e524c4064db9)

![Screenshot_20231025-222231](https://github.com/Team-xManager/xManager/assets/1783037/2604baf2-300f-4ed2-b017-8532f577208e)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by OldBuffGuy** [comment]
Isn't it possible xManager's patching procedure could be causing the issue?

**Comment by MadeInDutch** [comment]
I tried using support. The Telegram channel doesn't allow anyone to post. My Reddit post got taken down immediately (no reason given). Can't you just fix the issue on here? It's clearly a bug relating to xManager.
