### ISSUE TITLE
WearOS support

### ISSUE THREAD

**Issue by korakoe** [Team-xManager/xManager#393]
### Description of the new feature / enhancement

- 1 With the new version of Spotify on WearOS, you can now directly stream from the watch, however, it is cumbersome and hasn't yet been patched

- 2 the song select menu doesn't allow you to select individual songs, so perhaps a reworked UI

- 3 the WearOS app should have most of the features that the patched mobile app does, including infinite skips, adblock, etc.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
