### ISSUE TITLE
The spotify cannot load the lyrics

### ISSUE THREAD

**Issue by gntxy** [Team-xManager/xManager#396]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: xiaomi redmi note 9
- Android Version:  13
- ROM Version:  pixel experience android 13
- xManager Version:  last
```

### 📝 Description

I know this bug is not from xmanager, but maybe you guys can fix it??
I don't know why, but my friend who has never installed Spotify mod can load the lyrics, but I can't, even I have created a new account

### 📸 Screenshots

![Screenshot_20231104-222859_Spotify](https://github.com/Team-xManager/xManager/assets/86417999/8907f0b2-0c64-456c-9bee-6fa48883e2ab)

**Comment by AdiGro** [comment]
Spotify lyrics are premium now [for most users, it's still rolling out I believe]. 🤷 strangely the lyrics work for some songs and not for the rest. It's a server side thing tho, i doubt there's anything xmanager could do.

**Comment by gntxy** [comment]
> Spotify lyrics are premium now [for most users, it's still rolling out I believe]. 🤷 strangely the lyrics work for some songs and not for the rest. It's a server side thing tho, i doubt there's anything xmanager could do.

uhm it would be great if it could load all the lyrics.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
