### ISSUE TITLE
App functioning perfectly, but sound no longer works

### ISSUE THREAD

**Issue by 8gf555as** [Team-xManager/xManager#397]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Pixel 6 Pro
- Android Version:  Android 14
- ROM Version:  CalyxOS 5.0.2
- xManager Version:  5.0
```

### 📝 Description

1. Open app either via Manager Tools "Launch Patched App" or directly opening Spotify. Any version, Lite, Amoled, or Stock.
2. Navigate to a song or playlist or album.
3. Play the song.
4. Graphics/Video will roll, sound will not come out. 
...
Attempted with Stock and Amoledfrom versions 8.8.40.470 to 8.8.80.599. Same result.
The issue started at random. Was playing a song and the next song wouldn't play. Closed the app and opened again. Tried different VPN or no VPN. Attempted to clean cache and data from the app and from xManager. Attempted to restart phone, reinstall xManager, reboot phone. Issue still persists.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
