### ISSUE TITLE
Wave patch is not working 

### ISSUE THREAD

**Issue by laboosh56** [Team-xManager/xManager#398]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [x] I did a clean install of xManager
- [ ] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung s8 plus
- Android Version:  9
- ROM Version:  
- xManager Version:  5
```

### 📝 Description

Everytime I use Wave patch it always says streaming not allowed you have no active subscription.

### 📸 Screenshots

![Screenshot_20231110-112117_TIDAL](https://github.com/Team-xManager/xManager/assets/150463225/df598ac2-c306-4908-896c-37c97aa7da74)

**Comment by AOIK4ZUYA** [comment]
I made an account just to confirm that yes
I have the same problem

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
