### ISSUE TITLE
%s name app after reboot radio

### ISSUE THREAD

**Issue by grzech1991** [Team-xManager/xManager#400]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [ ] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Android Radio 7862
- Android Version:  12 (but true is 10)
- ROM Version:  i don't know
- xManager Version:  latest
```

### 📝 Description

After install app from xmanager, working great. But if i reboot the radio app name is change to %s and don't work ($s is connected still don't work)

Any have idea what is wrong?

### 📸 Screenshots

![image](https://github.com/Team-xManager/xManager/assets/99332031/2f9f18ba-248e-4dd6-b718-ec2b23f8d52b)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
