### ISSUE TITLE
Ad's started to appear out of nowhere and now i have ads for some podcast of Trevor Noah and Dwayne Johnson and some other's that can be closed with a cross sign but not this one

### ISSUE THREAD

**Issue by Hit4man47** [Team-xManager/xManager#401]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung M51
- Android Version: 13 
- ROM Version:  stock
- xManager Version:  5.0
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![Screenshot_20231114-172226_Spotify](https://github.com/Team-xManager/xManager/assets/94435395/149643e7-56ab-41fb-8ab1-52d43793fd8d)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
