### ISSUE TITLE
installed version not matching newest version even after update

### ISSUE THREAD

**Issue by temptationstairway** [Team-xManager/xManager#403]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung S23 Ultra
- Android Version: Android 13
- ROM Version: stock 
- xManager Version: v5.1
```

### 📝 Description

1. open x manager
2. notice new update and press the newest update for stock patched
3. app successfully downloads update for spotify patch
4. after update, both app (spotify) and x manager say that it's the same as it was before the new download
5. deleting and reinstalling does not fix the issue

ive tried reinstalling and tried doing anything i could to fix it. spotify shows the version as the same one as before the update. it doesnt change even after a fresh install.

### 📸 Screenshots

![Screenshot_20231114_114736_xManager~2](https://github.com/Team-xManager/xManager/assets/84050105/cd86e7dc-dc2c-4119-963b-bcc8b50e0e2f)

![Screenshot_20231114_115637_Spotify](https://github.com/Team-xManager/xManager/assets/84050105/c6787d6a-d2fa-4884-8683-e4489170ec16)

**Comment by Tim-Odermatt** [comment]
i have the same problem, just for me it installs 8.8.36.522.
it is not a display problem, the installed Spotify is that "old" version, when i go into settings and look at the version.

Amoled Patched + Stock Patched
