### ISSUE TITLE
Can you add the ability to change the application region without using a VPN? 

### ISSUE THREAD

**Issue by Glazami** [Team-xManager/xManager#406]
### Description of the new feature / enhancement

like in a modified tiktok application, for example a mod from tiktokmodсloud or jaggu?
It would be very convenient I think for many.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
