### ISSUE TITLE
Error during Installation

### ISSUE THREAD

**Issue by cxl1b3r** [Team-xManager/xManager#423]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Motorola Moto G9
- Android Version: Android 11
- ROM Version: stock
- xManager Version: 5.1
```

### 📝 Description

Whenever I try to install any release and any version of the patched app, it downloads but while installing it gives an error stating "There was a problem while parsing the package." I have also noticed that the when the patched app downloads it only downloads 0.07 MB which is an oddly small size for any app. Screenshots attached for reference.

### 📸 Screenshots

![Screenshot_20231201-055312-782](https://github.com/Team-xManager/xManager/assets/96351476/4b13e848-1544-46e8-95dd-0561f91526c8)
![Screenshot_20231201-055649-016](https://github.com/Team-xManager/xManager/assets/96351476/d5099734-2c24-413c-93a8-cd67a9ea87ae)

**Comment by winpower21** [comment]
Same issue.
Device Model: Motorola Moto G72
Android Version: 12
xManager Version: 5.1

**Comment by Chris1320** [comment]
It seems like the link is broken. The `.apk` is actually an HTML file:

```html
<!-- most of the content omitted -->
<title>Dropbox - Link Temporarily Disabled - Simplify your life</title>
```

**Comment by Cristark02** [comment]
Same issue.
Device Model: Google Pixel 7a
Android Version: 14
xManager Version: 5.1

**Comment by zaydestic** [comment]
> Same here, 
> 
> - Device Model: Realme 3 Pro
> - Android Version: Android 12
> - ROM Version: Awaken 2.5
> - xManager Version: 5.1

Download from the mirror link it works.

**Comment by Omkaragrawal** [comment]
Same here on:

Device: Samsung A52S
Android Version: 13
Rom Version: OneUI 5.1
Xmanager version: XManager v5.1

**Comment by Chris1320** [comment]
> @zaydestic where can i find that opiton in UI?

There is also a "Mirror Link" button on the bottom-left part of the panel when you are downloading the `.apk` file.

**Comment by shriprasadD12** [comment]
Installation issue in Motorola E20 Fusion
 Android 12 Stock.

**Comment by Mickeygoat** [comment]
Same here on fairphone 4

**Comment by HBP87** [comment]
I am having the same issue on Galaxy S23 Ultra running on OneUI 6 (Android 14).

**Comment by FlagHere** [comment]
Same here and also the mirror link is working

**Comment by H3nnyM** [comment]
Same issue.
Device: Honor 90
Android Version: 13
MagicOS: 7.1
Xmanager 5.1

**Comment by H3nnyM** [comment]
> Same issue. Device: Honor 90 Android Version: 13 MagicOS: 7.1 Xmanager 5.1


My HONOR 50 works with V5.0 - also Android 13 MagicOS 7.1
Tried installing 5.0 on the HONOR 90, but it still shows the parsing error.

**Comment by xC3FFF0E** [comment]
Issue should be resolved by now. All links are up.
