### ISSUE TITLE
Make this app recognized in Android Auto

### ISSUE THREAD

**Issue by iamsank8** [Team-xManager/xManager#425]
### Description of the new feature / enhancement

Even thought the app works fine in phone, it doesn't gets recognized by Android Auto. so just to be able to play songs in car, I had to install normal version.

**Comment by yankarinRG** [comment]
Hello, had the same problem and solved with the following steps:

1. Open your phone's Settings app.
2. Tap Connected devices And then Connection preferences.
3. Tap Android Auto.
4. Scroll to Version at bottom and tap ~10 times to unlock Developer Mode
5. Click kebab icon at top right -> Developer settings
6. Scroll to bottom and enable “Unknown sources”
7. Exit and re-open Android Auto

Spotify should now be visible!"

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
