### ISSUE TITLE
no installing prompt

### ISSUE THREAD

**Issue by A0Y68** [Team-xManager/xManager#426]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Redmi Note 9 Pro
- Android Version:  13
- ROM Version:  Pixel Experience Android 13(Plus)
- xManager Version:  5.1
```

### 📝 Description

The download button appears, and when i click on it, it doesnt show the downloading progress bar. it only works if i have spotify installed from play store or any 3rd party apps, butit ends with not downloading. idk if its a problem with the ROM as it shown my device model as"Redmi Note 10 Lite" instead of "Redmi Note 9 Pro".

**Comment by y-ziane** [comment]
+1

**Comment by DarkCrypt** [comment]
Try:

1. Clear Xmanager's cache and retry downloading.

2. Download with MIRROR LINK.

**Comment by xC3FFF0E** [comment]
All links should be working as of now. Try again to download. If the issue persists, visit one of our support teams. Thanks!
