### ISSUE TITLE
Package parsing error

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [Team-xManager/xManager#427]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [ ] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: SM-G991U (S21 5G) (has several software bugs that are unfixable) 
- Android Version: 13
- ROM Version: ??
- xManager Version: System says 5.1 (unable to find in app, and I downloaded latest from website)
```

### 📝 Description

1. Install the manager
2. Attempt download (Amoled version) (This sometimes doesn't work)
3. Click install and receive failed to parse package error in which my system states its not a valid package.
...

**Comment by xC3FFF0E** [comment]
Duplicate Issue: https://github.com/Team-xManager/xManager/issues/423
