### ISSUE TITLE
Spotify local files

### ISSUE THREAD

**Issue by MajorasMaks** [Team-xManager/xManager#429]
The local files option is very glitchy in spotify so half the time they appear and half the time they don't, so I was wondering if there is a way to make a feature that would make sure they appear.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
