### ISSUE TITLE
play store update

### ISSUE THREAD

**Issue by kelvinkad** [Team-xManager/xManager#431]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung galaxy s9  
- Android Version:  10
- ROM Version: stock  
- xManager Version:  5.2
```

### 📝 Description

1. download latest Spotify amoled 8.8.90.893
2.install
3. open play store 
...
spotify appears as update. I always used xmanager this exactly way, and never happened to appear on play store updates. this last version it's happening this.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by kelvinkad** [comment]
All topics are closed on telegram channel. That's why I came here. But thanks for answering.

**Comment by xC3FFF0E** [comment]
> All topics are closed on telegram channel. That's why I came here. But thanks for answering.

Go to our Discord support channel.
