### ISSUE TITLE
Tidal says I've "reached my streaming limit" and can't use the app at all anymore

### ISSUE THREAD

**Issue by TheAutumnApple** [Team-xManager/xManager#437]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Redmi Note 9 Pro
- Android Version: Android 12
- ROM Version: stock
- xManager Version: 5.2
```

### 📝 Description

Been using the WAVE package for a good while and it's been pretty awesome but now it gives me an error that prevents me to play music that says I've "reached my streaming limit" and now can't do anything anymore. I've tried installing an older version but it gets the same error. I am using my VPN to put myself in USA and, as I said, it was working just fine before

### 📸 Screenshots

![Screenshot_2023-12-18-18-09-46-931-edit_com aspiro tidal](https://github.com/Team-xManager/xManager/assets/133878461/9497a973-8744-4312-9b09-b3836ee97309)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
