### ISSUE TITLE
Parsing patches

### ISSUE THREAD

**Issue by thecrazyfish** [Team-xManager/xManager#442]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Xiaomi mi 10t pro 
- Android Version:  android 12
- ROM Version:  stock
- xManager Version:  latest
```

### 📝 Description

1. I tried to install any version, lite, original, amoled, wave, I get same error always, package cannot be parsed. 
2.
3.
...

**Comment by ulisesoldemar** [comment]
Use the mirror.

**Comment by preto677** [comment]
I have the same issue, downloaded packages are very small 60-70kb and there is an error with parsing the package.. I don't see any option to see mirrors, I use latest xmanager

**Comment by Hanz-212** [comment]
same issue with 60kb download only

**Comment by preto677** [comment]
I have fond the mirror button now, it's not visible for a very long time, since main download is only 60kb

Also downgraded to 5.1, seems like main links of some older versions work there

**Comment by lemonekq** [comment]
wave is just an not working shitty tidal version. Just use mirrors

**Comment by xC3FFF0E** [comment]
All links are up. Try to redownload again. If the issue persists, visit one of our support channels. Thanks!
