### ISSUE TITLE
No Internet connection 

### ISSUE THREAD

**Issue by M0rta4aa** [Team-xManager/xManager#444]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  
- Android Version:  
- ROM Version:  
- xManager Version:
```

### 📝 Description

Cant connect to spotify with my data mobile

### 📸 Screenshots

![Screenshot_20231226_211206_Spotify](https://github.com/Team-xManager/xManager/assets/154926828/205af61a-a602-42c6-a6e8-8e87a26e6504)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
