### ISSUE TITLE
App shares data with tens (possibly hundreds?) of companies

### ISSUE THREAD

**Issue by kszkristof** [Team-xManager/xManager#446]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Pixel 6 Pro
- Android Version:  14
- ROM Version:  stock
- xManager Version:  latest 5.2
```

### 📝 Description

Reproducing: open the app after updating to / installing latest version
Expected: the app opens without any popups
In reality, the app prompts you to accept a bunch of 3rd party companies' tracking cookies. This is a huge security concern and I see no reason why an app whose sole purpose is to download files from the Internet would need this. 
The popup is one of the annoying ones as well, taking about 10 minutes to disable every one of the companies' "legitimate interest" tracking. 
Why was this necessary? Were earlier versions tracking and selling our data as well, it's only the latest version that this became apparent in or was this tracking introduced now?

**Comment by Th3-A6add0n** [comment]
Share screenshots/proof.

**Comment by kszkristof** [comment]
[Here](https://github.com/Team-xManager/xManager/assets/64156310/197bec9c-02d4-4d7c-99d8-3672bf3f06c9) you go. It was added in the latest release.

**Comment by Th3-A6add0n** [comment]
> [Here](https://github.com/Team-xManager/xManager/assets/64156310/197bec9c-02d4-4d7c-99d8-3672bf3f06c9) you go. It was added in the latest release.

You can turn this OFF in settings, just turn off ads in xManager settings.

**Comment by xC3FFF0E** [comment]
If you are talking about GDPR (EEA and UK), you should definitely read this: https://support.google.com/admob/answer/7666366?ref_topic=10303737

**Comment by kszkristof** [comment]
> > [Here](https://github.com/Team-xManager/xManager/assets/64156310/197bec9c-02d4-4d7c-99d8-3672bf3f06c9) you go. It was added in the latest release.
> 
> You can turn this OFF in settings, just turn off ads in xManager settings.

The thing is, I didn't *want* to turn off ads - I wanted to support the developer(s) but didn't know this app also collected data. I just decided to donate a few bucks instead and now I'll disable the ads (I think you don't make very much off that one ad I watch every few months when I update anyway). 

Is data collection stopped completely by turning ads off?

> If you are talking about GDPR (EEA and UK), you should definitely read this for better understanding and how it work: https://support.google.com/admob/answer/7666366?ref_topic=10303737

So it's not the app itself but Google's AdMob which you use to monetize the app that is collecting the data and it's became mandatory for every app to implement asking for consent on their own?

**Comment by Th3-A6add0n** [comment]
> So it's not the app itself but Google's AdMob which you use to monetize the app that is collecting the data and it's became mandatory for every app to implement asking for consent on their own?

Yes

**Comment by Th3-A6add0n** [comment]
@xC3FFF0E this can be **closed** now.

**Comment by szmarczak** [comment]
> > [Here](https://github.com/Team-xManager/xManager/assets/64156310/197bec9c-02d4-4d7c-99d8-3672bf3f06c9) you go. It was added in the latest release.
> 
> You can turn this OFF in settings, just turn off ads in xManager settings.

But the thing is that in order to turn this off you have to either accept it or spend 3 minutes turning every single checkbox off. Or you could ask this on the second application run so people can go to settings and turn off the ads before the popup happens.

Or provide a `Reject all` button. Actually, not providing it is against the GDPR since declining should be as easy as accepting.

**Comment by szmarczak** [comment]
> If you are talking about GDPR (EEA and UK), you should definitely read this for better understanding and how it work: https://support.google.com/admob/answer/7666366?ref_topic=10303737

That's a blatant lie. Google and other companies such as Meta are known for selling personal data. FYI, according to the GDPR, personal data is anything that can be used to narrow down the population to find you. Given enough personal data you can be identified as a single entity.

For example, selling information such as `user h7Fv5 likes apples` is in violation of GDPR if the user had not given explicit consent.
