### ISSUE TITLE
Need to be updated

### ISSUE THREAD

**Issue by GITHUBGamer01** [Team-xManager/xManager#448]
Its not the new 8.9.6.458 it's the 8.8.96.364
![Screenshot_20240120-222956](https://github.com/Team-xManager/xManager/assets/106441977/3ba0682d-7a2d-4220-ba16-7cbde62fbff5)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
