### ISSUE TITLE
Spotify Download

### ISSUE THREAD

**Issue by DeadSecTr** [Team-xManager/xManager#449]
Will be song download ever possible one time? 

Or is this just a dream?

Btw...big thx for the great work

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
