### ISSUE TITLE
Android TV Edition

### ISSUE THREAD

**Issue by leonistlol1** [Team-xManager/xManager#452]
### Description of the new feature / enhancement

A Android TV Edition of XManager will be good

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered. 

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
