### ISSUE TITLE
Wave edition is not Premium, just the normal app?

### ISSUE THREAD

**Issue by arduinoturkbatu** [Team-xManager/xManager#453]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A34
- Android Version:  Android 14
- ROM Version:  stock
- xManager Version:  5.2
```

### 📝 Description

1. Select Waze version
2. Install Latest (2.93.1)
3. Open the Tidal app that installed
4. Login with previously created account
5. Select a song

Here is the bug comes in. It says "TIDAL HiFi Plus" on Settings^1st image (🎚️ > Manage account) but when I try to listen to the songs, it needs a subscription to play^2nd image.

### 📸 Screenshots

![1](https://github.com/Team-xManager/xManager/assets/50751564/e75df89a-512c-4cd7-b675-009c40fe8adc)
![2](https://github.com/Team-xManager/xManager/assets/50751564/d2f1a020-8a1a-4b56-8a7d-5ce5b1e1d316)

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered. 

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
