### ISSUE TITLE
Premium Features not working in the latest version

### ISSUE THREAD

**Issue by BedBug2479** [Team-xManager/xManager#455]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  OnePlus 9 Pro
- Android Version:  13.1
- ROM Version:  stock
- xManager Version:  5.2
```

### 📝 Description

The Premium featues are not working in the latest version 8.9.10.616

I did a clean install but still not working

Now using the previous version 8.8.96.364

### 📸 Screenshots

![Screenshot_2024-02-09-11-35-55-33_a5c01c4563cf301fdcc1087d689ebdc7](https://github.com/Team-xManager/xManager/assets/43089040/eeed1524-ade3-43b7-bcea-f7d26de2f072)
![Screenshot_2024-02-09-11-36-25-17_0438eb925998df20b3482ec25499d226](https://github.com/Team-xManager/xManager/assets/43089040/5a9aa886-2f43-4a37-b29c-8602ea313940)
![Screenshot_2024-02-09-11-36-30-10_0438eb925998df20b3482ec25499d226](https://github.com/Team-xManager/xManager/assets/43089040/8de63094-cdc3-4f1f-9406-0ca458f55663)

**Comment by Ponleuz11** [comment]
@BedBug2479 i got that too

**Comment by JustAnotherOneee** [comment]
Is that gonna be updated?

**Comment by Ponleuz11** [comment]
@JustAnotherOneee already but it doesn't work

**Comment by AIRIE0122** [comment]
For now I think you can just use version 8.8.96.364 for now, while they fix the latest version problem. As I also got that problem

**Comment by AIRIE0122** [comment]
> I can't download any version from xmanager

You can download patched 8.8.96.364 tru "mirror download"
Basically when the download ui pops up, immediately click mirror link button and it will take you to media fire, thus you can download the patched as normal. but do keep in mind, as for now the patch will not work on the latest version. So I recommend you download it older version of the patch, at best version 8.8.96.364.

**Comment by JustAnotherOneee** [comment]
Downloaded older version by mirror link and everything is working. Thanks you for helping

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by kelvinkad** [comment]
we cannot talk anything on telegram channel, so it's useless
