### ISSUE TITLE
Spotify 8.9.10.616 [AB Experimental] not work 

### ISSUE THREAD

**Issue by Ponleuz11** [Team-xManager/xManager#456]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Realme C15 Qualcomm Edition 
- Android Version: 11(R)
- ROM Version:  stock (Color os)
- spotify Version: 8.9.10.616 [AB Experimental]
```

### 📝 Description

The bug is the version that release february 7th 11:10 (cambodia time) not work. after install it show premium option and the spotify plan is Free plan.
please Xmanager team fix that.
from me Ponleuz 

### 📸 Screenshots

![Screenshot_2024-02-09-13-24-55-73_0438eb925998df20b3482ec25499d226](https://github.com/Team-xManager/xManager/assets/159515011/3d565bb4-f439-4481-be4b-25f61f1f2125)
![Screenshot_2024-02-09-13-25-50-96_0438eb925998df20b3482ec25499d226](https://github.com/Team-xManager/xManager/assets/159515011/5a72b6e9-be99-4f42-a17b-565a466d1985)
![Screenshot_2024-02-09-13-32-49-74_0438eb925998df20b3482ec25499d226](https://github.com/Team-xManager/xManager/assets/159515011/c1f08f07-35df-414d-8838-fd153e701a44)

**Comment by YeetingWaterbottle** [comment]
Try and clear the cache of the Spotify app and relaunch to check

**Comment by Ponleuz11** [comment]
@YeetingWaterbottle not working

**Comment by leon00355** [comment]
It's not working to me either. Pls fix it

**Comment by Ponleuz11** [comment]
@leon00355   use spotify version 8.8.96.364 Xmanager

**Comment by magnumninja** [comment]
> @leon00355 use spotify version 8.8.96.364 Xmanager

This is something i also tried but ive watched the same tiktok ad and temu ad about 30 times and cant get it to download

**Comment by pingal79** [comment]
When you select the version, You have to click very fast on the mirror Link on the left bottom
