### ISSUE TITLE
Shuffle bug. Shuffle is on although i turned it off

### ISSUE THREAD

**Issue by Janclub** [Team-xManager/xManager#457]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: samsung galaxy a52
- Android Version:13  
- ROM Version:stock
- xManager Version:  newest
```

### 📝 Description

1.You should fix the shuffle bug
2.
3.
...

### 📸 Screenshots

![Screenshot_20240210_012905_Spotify](https://github.com/Team-xManager/xManager/assets/123305411/ffb1d305-038f-4e03-b1e6-f4e51f9ff97a)

**Comment by gnayiqnat** [comment]
Can confirm, also have the same issue.

Device Model: Samsung Galaxy A34
Android Version: 14 (One UI 6)
Downloaded from mirror link

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
