### ISSUE TITLE
Impossible to download file, slow.. unusable 

### ISSUE THREAD

**Issue by Kostas9999** [Team-xManager/xManager#461]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  
- Android Version:  
- ROM Version:  
- xManager Version:
```

### 📝 Description

1.
2.
3.
...

**Comment by Kostas9999** [comment]
useless, cant download file..

**Comment by xC3FFF0E** [comment]
Closing. No sufficient information.
