### ISSUE TITLE
3rd party companies' tracking cookies : we need to click on 50+ buttons to disable all "legitimate interest" cookies. It's infuriating.

### ISSUE THREAD

**Issue by Elaws** [Team-xManager/xManager#463]
### Description of the new feature / enhancement

When installing the app for the first time, we are welcomed with a screen about 3rd party companies' tracking cookies. If one wants to disable all of them (especially the "legitimate interests", which are all activated by default), he needs to click on more than 50 buttons to disable them one by one.

Are there alternatives to get rid of this pure r/assholedesign (this is obviously not referring to the authors of xManager) ? 

Thank you very much.

**Comment by xC3FFF0E** [comment]
Duplicate: https://github.com/Team-xManager/xManager/issues/446

Closing
