### ISSUE TITLE
Why are there 4 xmanager websites, are the others fake?

### ISSUE THREAD

**Issue by XaviXE** [Team-xManager/xManager#464]
I founded:
xmanager.app
xmanagerapp.com
xmanager.org
xmanagerapp.net

**Comment by viledissociation** [comment]
the one they link on their github (here) is [xmanagerapp.com](https://www.xmanagerapp.com/). I been using apk's such as this one for ages, and I always see fake website with malicious apk's. I would assume that the others are fake. Personally I only download xmanager or other similar app's from their github repositories so I don't have to deal with fake websites.

**Comment by XaviXE** [comment]
So then I think I screwed up, I barely remember (I think it was xmanager.org) but I downloaded the xmanager apk and sent the mirror link to my father's phone to download the Spotify apk, it didn't look suspicious anyway. Is my dad's phone in trouble?

**Comment by viledissociation** [comment]
Yeah, I checked some stuff, the domain is registered at namecheap (different from the official website I know) and namecheap is kind of known for scam domains. If you want you can try to find out more contact on who owns the website by looking at [this](https://www.whois.com/whois/xmanager.org) and writing an email to abuse@namecheap.com
I also checked their website and tried to get the apk to check if someone just hosts a different website to get people to download the same app, but I couldn't get the download button to give me the apk, also I would've done a virus check on it.. 
Anyways to your father's phone, if the mirror link is the same link as in the original apk, then it should download the right file for your dad (i.e. it should be fine) but the xmanager apk you got might be infected with malware.

**Comment by XaviXE** [comment]
Thanks for the research, I'll write to this email to explain what is happening. The device in which I installed xmanager is fine, I installed a different OS in it and wiped all the data but I have a backup so if I can't download the apk from the fake sites I will look in the backup :) Also I will try to get the apk from my father’s phone since I don't think I deleted it from the downloads folder.

**Comment by viledissociation** [comment]
Yeah, you can check if the links match or if the apks match

**Comment by Paradox9955** [comment]
> So then I think I screwed up, I barely remember (I think it was xmanager.org) but I downloaded the xmanager apk and sent the mirror link to my father's phone to download the Spotify apk, it didn't look suspicious anyway. Is my father's phone in trouble?

As far as I know, all of the fake websites link to this repo. So your father's phone will be alright. And also, xmanagerapp.com is the only website the xmanager team owns. All the other ones are fake, and I don't know why they exist.

**Comment by energ0n** [comment]
As already stated above, https://www.xmanagerapp.com/ is the only official website. All others are fake. 

Fortunately most of the fake websites are still linking directly to the official xManager APK from this repo so if someone messed up and used the wrong website they are likely ok... but uninstalling and using this repo or the official website is recommended just in case. 

It is unknown what the goal of the fake sites is -- some have links to fake social media groups, most have false information about app features, some run ads. Possibly a bait and switch, swapping in a malicious file later on. Regardless, this repo and the website point to all the official sources, no reason to guess with Google or anything else.
