### ISSUE TITLE
Need a fix for the download issue

### ISSUE THREAD

**Issue by GameMaster007** [Team-xManager/xManager#469]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Oneplus Nord 2 5G
- Android Version:  13
- ROM Version:  13.0
- xManager Version: 5.2
```

### 📝 Description

1. I have tried to use VPN changed the DNS and it doesn't work.
2. I have been travelling and checked too so I rule out it is not regional issue.
3. Also the downloading in the app is not working and is extremely buggy sometimes you have to lock and unlock the screen to make it work (Idk how)
4. No ISP issues too so can rule that out too.
5. It seems to be the apps issue completely and there are many who has the same issue it feels like using the app is just for looks.
6. Currently I am using mediafire link to download the apps but I am not comfortable with it please fix it as soon as possible I have 
seen the previous issue of low download speed please fix it I love this app and it hurts me that I can't use to its fullest potential.

**Comment by xC3FFF0E** [comment]
Sorry for the inconvenience that the app caused you. The downloading issue is now fixed on the latest version (5.3). Kindly update to the said version. Thanks!
