### ISSUE TITLE
unable to do anything with the app

### ISSUE THREAD

**Issue by Teknoky100** [Team-xManager/xManager#470]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:realme GT 5G 
- Android Version:13
- ROM Version:realme UI 4.0
- xManager Version:5.2
```

### 📝 Description

The app is fucking trash, tried downloading the wave app and had an insane stupid slow download speed without even being able to install after 100% and guess what? it's worse, I let it sit for like half an hour or so, get back to my phone and my phone was in a damn coma, the app crashed when I got back to it I used my phone a little and then I got on a blackscreen I tried to force restart but it didn't work, it just landed me on the lockscreen after a while, used my phone for a while and it restarted after like 30 seconds after my try, I will never try this thing again 😂

**Comment by xC3FFF0E** [comment]
Sorry for the inconvenience that the app caused you. The downloading issue is now fixed on the latest version (5.3). Kindly update to the said version. Thanks!
