### ISSUE TITLE
Can't download music 

### ISSUE THREAD

**Issue by FouadNassif** [Team-xManager/xManager#480]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  a52
- Android Version:  14
- ROM Version:  
- xManager Version:
```

### 📝 Description

1. Cant download any.music
2.
3.
...

**Comment by energ0n** [comment]
This repo is specifically for the xManager app only -- not any mods.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
