### ISSUE TITLE
Not able to fetch lyrics of any song

### ISSUE THREAD

**Issue by Khushal-gupta22** [Team-xManager/xManager#484]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [x] I did a clean install of xManager

### ℹ Information

```markdown
- Device Model: Realme Narzo 60 5G
- Android Version: 14
- ROM Version:  stock
- xManager Version:  5.5
```

### 📝 Description

Not able to get lyrics of any song. I think Spotify has blocked this from their server side.

### 📸 Screenshots

!Issue Iamge](https://github.com/Team-xManager/xManager/assets/106315796/b4c4a3bd-baae-4698-995f-4348a09f9b77)

**Comment by xsaxsaxsa** [comment]
Same problem

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
