### ISSUE TITLE
New Release Spotify 

### ISSUE THREAD

**Issue by Emanuele-1998** [Team-xManager/xManager#485]
I'm posting here because the Xmanager Telegram group is closed, but why are there no more new versions of Spotify on the Xmanager app? I see on other sites where I only post screens where there is the name of a modder. Thanks for the work done so far, I hope to have an answer.

![Screenshot_20240508_160957_Samsung Internet.jpg](https://github.com/Team-xManager/xManager/assets/67318166/53c6b4de-c849-458a-be88-84336b6deec9)

![Screenshot_20240508_161012_Samsung Internet.jpg](https://github.com/Team-xManager/xManager/assets/67318166/97cc48a6-77b5-45c4-ab11-e863aed7502a)

**Comment by energ0n** [comment]
Your screenshots are from unofficial releases with fake version numbers to fool users into thinking they are running newer builds. 

Also...
This repo is specifically for the xManager app only -- not any mods.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels. And the first thing you should do when joining either of those support channels is reading the FAQ as your issue will likely be answered.

xManager Support Links:
•[Discord](https://discord.gg/dnpKn5Wufm)
•[Telegram](https://t.me/xManagerSupport)
