### ISSUE TITLE
Downloading playlist on spotify light

### ISSUE THREAD

**Issue by Amr-Samy** [Team-xManager/xManager#498]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  samsung a23
- Android Version:  14
- ROM Version: light  1.9.0.43809
- xManager Version:  5.5 latest
```

### 📝 Description

1.when switching the download button for any playlist 
2.It shows waiting for dowload then its gone and no thing is downloaded
3.tried vpn but the same 
Spotify light doesnot have storage permission and didnot find a way to grant that .

### 📸 Screenshots

![Screenshot_20240531_192745_Spotify Lite](https://github.com/Team-xManager/xManager/assets/36173696/86e181bd-3117-4b15-bcfe-f7546bf76fbb)

**Comment by Lolen10** [comment]
You can't download any songs w/o Spotify Premium. It's a server-side check which cannot be bypassed by any modded Spotify apps. So it's not a bug, it's intended behaviour.

**Comment by Amr-Samy** [comment]
> You can't download any songs w/o Spotify Premium. It's a server-side check which cannot be bypassed by any modded Spotify apps. So it's not a bug, it's intended behavior.

@Lolen10 Thanks for explanation
