### ISSUE TITLE
Lyrics never load

### ISSUE THREAD

**Issue by StupidRepo** [Team-xManager/xManager#506]
Not sure if this is a bug with *the green music streaming app* on the normal Play Store version, but I've noticed lyrics always fail to load, even with songs that have the little [LYRICS] badge. Could this please be fixed? Thanks in advance!

**Comment by balaga-yavanika** [comment]
Yeah. Same issue 😪 Please fix this 🙏 ASAP.

**Comment by APN420** [comment]
Yes please bring the next update for that 🙏🙏🙏

**Comment by jyotirmaybarman** [comment]
+1

**Comment by skroobs4** [comment]
Lyrics never load for me either!

**Comment by ShineUA** [comment]
Also for me.

**Comment by FakeId64** [comment]
+1

**Comment by NerdTrux** [comment]
Upvote, y'all are the best👍🏼

**Comment by ShineUA** [comment]
We need lyrics

**Comment by rickynolep** [comment]
It's been so long since the last update, Upvoted!!

**Comment by BakerBunker** [comment]
Since the lyric is blocked for non-premium accounts, maybe the patch can intercept the request of lyric and replace it with api call to open lyric database like [lrclib](https://lrclib.net/docs)

**Comment by StupidRepo** [comment]
> Since the lyric is blocked for non-premium accounts, maybe the patch can intercept the request of lyric and replace it with api call to open lyric database like [lrclib](https://lrclib.net/docs)

Yes, I noticed a few minutes ago. I'm sure there may be a way to disable the lyric cap as the preview still works (so it should be able to get the full thing unless their API on the backend is smart and blocks that?)

**Comment by Birraque** [comment]
Also confirming that lyrics doesn't working

**Comment by BakerBunker** [comment]
> > Since the lyric is blocked for non-premium accounts, maybe the patch can intercept the request of lyric and replace it with api call to open lyric database like [lrclib](https://lrclib.net/docs)
> 
> Yes, I noticed a few minutes ago. I'm sure there may be a way to disable the lyric cap as the preview still works (so it should be able to get the full thing unless their API on the backend is smart and blocks that?)

Currently for non-premium accounts, only first five lines are displayed, also reported at [this reddit thread](https://www.reddit.com/r/truespotify/comments/1chf942/spotify_premium_to_see_the_lyrics/)

**Comment by dilinzel-ine** [comment]
Well, does that mean we aren't gonna get lyrics update here? Or are we ?

**Comment by StupidRepo** [comment]
> > > Since the lyric is blocked for non-premium accounts, maybe the patch can intercept the request of lyric and replace it with api call to open lyric database like [lrclib](https://lrclib.net/docs)
> > 
> > 
> > Yes, I noticed a few minutes ago. I'm sure there may be a way to disable the lyric cap as the preview still works (so it should be able to get the full thing unless their API on the backend is smart and blocks that?)
> 
> Currently for non-premium accounts, only first five lines are displayed, also reported at [this reddit thread](https://www.reddit.com/r/truespotify/comments/1chf942/spotify_premium_to_see_the_lyrics/)

Yeah I know that, but what I'm saying is does the API used for obtaining the full lyrics detect if you've hit the cap on the backend or no?

**Comment by rickynolep** [comment]
if we can't access the lyrics because its blocked, isn't there an api or something like that to directly take lyrics from musixmatch or any lyrics provider to essentially replace the old lyrics? just like spicetify

**Comment by Felixzhangmingzhe** [comment]
> if we can't access the lyrics because its blocked, isn't there an api or something like that to directly take lyrics from musixmatch or any lyrics provider to essentially replace the old lyrics? just like spicetify

Spicetify can't load lyrics either.
I'm on windows 11.

**Comment by SolsticeSpectrum** [comment]
> > if we can't access the lyrics because its blocked, isn't there an api or something like that to directly take lyrics from musixmatch or any lyrics provider to essentially replace the old lyrics? just like spicetify
> 
> Spicetify can't load lyrics either. I'm on windows 11.

use lyrics-plus for spicetify https://github.com/spicetify/cli/tree/master/CustomApps/lyrics-plus

**Comment by rickynolep** [comment]
> > > if we can't access the lyrics because its blocked, isn't there an api or something like that to directly take lyrics from musixmatch or any lyrics provider to essentially replace the old lyrics? just like spicetify
> > 
> > Spicetify can't load lyrics either. I'm on windows 11.
> 
> use lyrics-plus for spicetify https://github.com/spicetify/cli/tree/master/CustomApps/lyrics-plus

Or Beautiful Lyrics if you want some fancy custom lyrics page and Fullscreen page
https://github.com/surfbryce/beautiful-lyrics

**Comment by xC3FFF0E** [comment]
Lyrics are now server-sided. Closing,

**Comment by SolsticeSpectrum** [comment]
> Lyrics are now server-sided. Closing,

Why are you guys so much against replacing lyrics providers like both spicetify and EeveeSpotify have available? You could even check out the respective spicetify plugin and EeveeSpotify implementations to see how it's done. If it's because you don't wanna add any features that should not be available, keep in mind that you're already doing so with bunch of other stuff so it doesn't really matter. At least provide some sort of guide to mod it in ourself.

**Comment by StupidRepo** [comment]
XManager devs are lazy? That's why.

**Comment by rickynolep** [comment]
> XManager devs are lazy? That's why.

Welp, I guess either I'm going to switch to (Revanced) YouTube Music, wait for a new Spotify patch dev, or do nothing about it and buy Spotify premium
