### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by siddardhaks** [Team-xManager/xManager#507]
### Description of the new feature / enhancement

- Add support for showing the app on Android Auto
- Show album art of currently playing songs, next, previous, pause, etc 
- Extra cool if it can let me go to my library and select a playlist or a song from my library

**Comment by glennvantorre** [comment]
> ### Description of the new feature / enhancement
> * Add support for showing the app on Android Auto
> * Show album art of currently playing songs, next, previous, pause, etc
> * Extra cool if it can let me go to my library and select a playlist or a song from my library
> 
> ### 📸 Screenshots
> _No response_

There is a known bug in Android auto however when developer settings are enabled and "Unknown sources" ticked. It will only one show up 50/50. So if the music app doesn't pop up in Android auto. Reconnect your phone to your car and let it load again. It helps sometimes to open the app first and connect to your car with the app open :)

Hope this helps

**Comment by siddardhaks** [comment]
Thanks for those who replied, this worked! For anyone else looking at this or searching for this, you can enable developer mode by opening the Android Auto settings on your phone, then clicking repeatedly on the "version" for 10 times. Then you can tap on the three dots on top right to go to Developer settings, and enable "Unknown sources" by checking the box next to it. Hope it helps somebody. Sorry for opening an issue about someone that was already supported.

**Comment by siddardhaks** [comment]
Thanks for those who replied, this worked! For anyone else looking at this or searching for this, you can enable developer mode by opening the Android Auto settings on your phone, then clicking repeatedly on the "version" for 10 times. Then you can tap on the three dots on top right to go to Developer settings, and enable "Unknown sources" by checking the box next to it. Hope it helps somebody. Sorry for opening an issue about someone that was already supported.
