### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by mine-nandha** [Team-xManager/xManager#514]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Iqoo Neo 9 Pro
- Android Version:  14
- ROM Version:  stock
- xManager Version:  latest
```

### 📝 Description

1. When I open the app, try to download any assets inside the app, it opens a link and it says file not found
2.
3.
...

### 📸 Screenshots

![Screenshot_20240719_043611](https://github.com/user-attachments/assets/3504aaea-f856-4e0b-bbfe-6a0a800da0a7)

**Comment by carbonarahater** [comment]
same

**Comment by Caylor777** [comment]
Same

**Comment by chickendrop89** [comment]
I am having the same issue with all variants

**Comment by Element21** [comment]
This looks to me like a Spotify mass takedown of modded clients. Why would the dev(s) take down ALL of the download links at the same time everyone's client crashes?

**Comment by APN420** [comment]
It is really sad but i think they took the mod down. I cant also use it anymore. It doesnt let me open the app. Either the mod uses a too old version or spotify tooked a massiv Ban

**Comment by TheUnknownVessel** [comment]
I thought i was going crazy as it was working this morning. I just wanted to listen to my music in peace without ads

**Comment by BigSmug** [comment]
Same

**Comment by iEatP0op7** [comment]
same

**Comment by mine-nandha** [comment]
Are there any alternatives?

**Comment by saltsoftdrink** [comment]
@xC3FFF0E please take a look

**Comment by blepdoge** [comment]
Same here, pixel 7a on A14

**Comment by Narmis-E** [comment]
We had a good run guys 😭
 hopefully some alternate method is found

**Comment by blepdoge** [comment]
Coming back on this, I installed an old version from jan 1. taken from their telegram, and I can open the app again, and play my stuff like before.

**Comment by Caylor777** [comment]
> Coming back on this, I installed an old version from jan 1. taken from their telegram, and I can open the app again, and play my stuff like before.

Can you send the telegram link

**Comment by Andoriax** [comment]
Super ditto.
None of the patched files are retrievable from fileport.io.
The recent version kept crashing this afternoon, so after clearing the data to no avail, I reinstalled Xmanager only to see more issues.

Typical that an update is errant. Please try again.

![Updates R Jokes_20240718](https://github.com/user-attachments/assets/a106d5f0-8a98-4a4b-b4fd-94a6ed338d03)

When it's fixed, y'all should give a solid listen to Degiheugi.

**Comment by blepdoge** [comment]
> > Coming back on this, I installed an old version from jan 1. taken from their telegram, and I can open the app again, and play my stuff like before.
> 
> Can you send the telegram link

It's just the telegram button on the x manager app

**Comment by Caylor777** [comment]
https://t.me/xManagerSupport/138498/216245?single

The link to a working apk if anyone wants it

**Comment by carbonarahater** [comment]
thanks

**Comment by mine-nandha** [comment]
I have a feeling that this app will also be taken down as we just let them know that this still works

**Comment by 5kyf1** [comment]
> https://t.me/xManagerSupport/138498/216245?single
> 
> The link to a working apk if anyone wants it

yep same problem, thanks for link.

As the op said, only the app for Jan works!

**Comment by WayStar794** [comment]
This happened a while ago, the Dropbox account hosting the files that xManager downloads got taken down, and the same appears to of happened with the cloud service they are using to host the files this time. (That or the cloud service is having major issues)
Last time within the same day he signed up for an alternate cloud service so we'll see what happens.

**Comment by HaterPass** [comment]
Anyone knows how to easily download all of my music from spotify, then? Just in case.

**Comment by APN420** [comment]
> Anyone knows how to easily download all of my music from spotify, then? Just in case.

There are many ways. I just used Seal to download the Music on YT or you can use the app esound

**Comment by xC3FFF0E** [comment]
Fresh links have been deployed in the xManager app. Closing.

**Comment by Andoriax** [comment]
> This happened a while ago, the Dropbox account hosting the files that xManager downloads got taken down, and the same appears to of happened with the cloud service they are using to host the files this time. (That or the cloud service is having major issues) Last time within the same day he signed up for an alternate cloud service so we'll see what happens.

@WayStar794, Thank you for identifying this.
Coincidentally, Microsoft's partnership with cybersecurity company, CrowdStrike, resulted in a global "meltdown" of everything dependent on MS 365 Apps, including my Verizon internet data which has slowed down today. CrowdStrike . . . apparently, the name says it all . . . coincidence, or Gates meddling with global affairs again?

====
@APN420  Nice mention! Thx!
=====

> Fresh links have been deployed in the xManager app. Closing.

Thank you @xC3FFF0E for working to resolve this.
