### ISSUE TITLE
Spotify crashes

### ISSUE THREAD

**Issue by DUSKz96** [Team-xManager/xManager#515]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Redmi Note 12 Pro 5G 
- Android Version:  14
- ROM Version:  Stock
- xManager Version:  5.6
```

### 📝 Description

 I tested with all versions but in all of them, when I go past the login screen, the application closes.

**Comment by Felixzhangmingzhe** [comment]
Same

**Comment by CornCube** [comment]
Bump, I'm having the same issue on a Pixel 7

**Comment by Epictetos** [comment]
I can confirm the same. Doesn't make sense that Spotify is now crashing andddd you can't download any version

**Comment by manning7A** [comment]
Same..No spotify no life

**Comment by Caylor777** [comment]
https://t.me/xManagerSupport/138498/216245?single

The link to the apk if anyone wants it

**Comment by sahiluchil** [comment]
Can confirm the same issue.

xManager version - 5.6
Spotify version - 8.9.18.512

**Comment by illtellyoulater** [comment]
Xmanager won't let me download the latest version and if I get fhat from telegram and install it, as others have noted it will crash

**Comment by sappyblaze** [comment]
its crashing for me too, re-downloaded the apk and everything

**Comment by DragonTheFolf** [comment]
Same thing is happening to me. Tried clearing cache and storage and nothing changed. All download links seem to be down.

**Comment by Caylor777** [comment]
> https://t.me/xManagerSupport/138498/216245?single
> 
> The link to the apk if anyone wants it

A apk that worked for me

**Comment by GYF0814** [comment]
crashed :(

**Comment by sho9029** [comment]
> https://t.me/xManagerSupport/138498/216245?single
> 
> The link to the apk if anyone wants it


The only solution for now, this worked for me

**Comment by naveenjujaray** [comment]
Same issue on samsung galaxy note 10 plus with the latest versions of xmanager and ambled patched apk.

**Comment by andrew020211** [comment]
Can confirm the same, and tested last 3 versions, all crashes.

**Comment by pseddonxvi** [comment]
I'm having the same issue too. I've tried updating the patcher to the latest version, nothing, I can't download .apk files as well.

**Comment by IonMakesGarbage** [comment]
same issue

**Comment by undefynedd** [comment]
xManager was crashing as well until I updated the apk, nothing is working.

**Comment by naveenjujaray** [comment]
This solution has been worked for me. Thank you. 
> > https://t.me/xManagerSupport/138498/216245?single
> > 
> > The link to the apk if anyone wants it
> 
> 
> The only solution for now, this worked for me

**Comment by gecko10000** [comment]
Apparently, 8.8.80.599 still works.

**Comment by IonMakesGarbage** [comment]
> https://t.me/xManagerSupport/138498/216245?single
> 
> The link to the apk if anyone wants it

im unable to download it from there so im a bit screwed...

**Comment by zNahuelz** [comment]
> Apparently, 8.8.80.599 still works.

Works for me too

**Comment by IonMakesGarbage** [comment]
i cant install any othet version because it just installs the latest one

**Comment by andrew020211** [comment]
> Apparently, 8.8.80.599 still works.

This one works

**Comment by IonMakesGarbage** [comment]
when i press to install that version it defaults to the latest

**Comment by TegarOktavian** [comment]
> https://t.me/xManagerSupport/138498/216245?single
> 
> The link to the apk if anyone wants it

Can confirm works for now, don't know for how long tho

**Comment by coltrain11** [comment]
Also 8.8.90.893 works for me

**Comment by SoupHuman** [comment]
how do I download the apk from the telegram link? do I need to have telegram to download it?

**Comment by illtellyoulater** [comment]
@SoupHuman  in XManager  scroll down and you'll find the links to the offical telegram channel with all the released versions

**Comment by n-ii-ma** [comment]
Same thing is happening.

**Comment by cmd420** [comment]
same

**Comment by mizuna25** [comment]
same here , i can't log in with any account i have, 
will be fix??

im on a lates version app on xmanager

**Comment by lolbee2705** [comment]
same here on s24!

**Comment by lolbee2705** [comment]
same here on s24 and a pop up message comes[
![SmartSelect_20240719_111029_Device care](https://github.com/user-attachments/assets/1bd3be05-51ef-4d31-a0f5-5e38f2f41b54)
](url)

**Comment by xC3FFF0E** [comment]
Up and running again. Closing.

**Comment by huase1015** [comment]
я скачиваю файл, у меня пишет не удалось обработать пакет, хотя файл полностью установлен
