### ISSUE TITLE
Download Error Stuck

### ISSUE THREAD

**Issue by Chiasaa** [Team-xManager/xManager#516]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung S20 FE
- Android Version:  13
- ROM Version:  What's "ROM Version" ?
- xManager Version:  5.6
```

### 📝 Description

1. I Click the download on the amoled black version
2. The popup progress of the download appear
3. The download always stuck at 0%, 2%, 4% or even 6% and the cancel button not wroking
...

### 📸 Screenshots

![Screenshot_20240719_114025_xManager](https://github.com/user-attachments/assets/c51b04ab-24b4-4cc5-9594-8549622c8418)

**Comment by chococade** [comment]
### I am also having this issue,please help

**Comment by Andrellet** [comment]
same here spotify start to crash and i have to uninstall and when i try to download the lastest version it got stock now i have no spoty

**Comment by Claw-Grip** [comment]
Yess. I thought it was my internet connection 🤔 crazy thing is that spotify still works fine on my old Samsung Galaxy. But on the S23 it crashes

**Comment by xC3FFF0E** [comment]
Fresh links have been deployed in the xManager app. Closing.

**Comment by Chiasaa** [comment]
> same here spotify start to crash and i have to uninstall and when i try to download the lastest version it got stock now i have no spoty

Yeah same, recently my spotify always crashes when i open it, that's im trying to reinstall it back, but the error appears

**Comment by Chiasaa** [comment]
> Fresh links have been deployed in the xManager app. Closing.

Appreciate it sir, but new problem accour, this pop-up appear after i click the download button.
![Screenshot_20240719_233649_Package installer](https://github.com/user-attachments/assets/f267eaa0-b313-40e5-979f-dc5016ad672d)
