### ISSUE TITLE
Download in Browser "Not Found"

### ISSUE THREAD

**Issue by MQX09** [Team-xManager/xManager#517]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:Xiaomi 13T Pro
- Android Version: 14 
- ROM Version: HyperOs 1.0.6.0 
- xManager Version:5.6
```

### 📝 Description

1.When I try to open the Spotify app it crashes
2.
![Screenshot_2024-07-19-07-54-52-212_com android chrome](https://github.com/user-attachments/assets/23f461fe-e3ae-4d5b-be60-9154fe416c64)

3.When I wanted When I tried to install the update, "Not Found"
...

### 📸 Screenshots

![Screenshot_2024-07-19-07-54-52-212_com android chrome](https://github.com/user-attachments/assets/6e7d6e16-cee3-449b-ad3a-9eaa34ead14a)

**Comment by Umang3143** [comment]
Yeah, even I am facing the same issue. "Not Found" is what the message is. Idk what is the exact problem...

**Comment by cmd420** [comment]
same exact problem

**Comment by Biggestprocrastinator** [comment]
https://t.me/xManagerSupport/138498/216245?single
