### ISSUE TITLE
Spotify crash and can't download any spotify version 

### ISSUE THREAD

**Issue by BrownyEz** [Team-xManager/xManager#518]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung s20 fe 5G 
- Android Version:  13
- ROM Version:  5.1
- xManager Version:  latest
```

### 📝 Description

1. When spotify is open, instant crash
2. Xmanager don't download any version of spotify

**Comment by remznwf** [comment]
Same for me 
Galaxy A33
1.Spotify crashes 
2.not redirected to download (no file)

**Comment by DeadPumpkin** [comment]
Clone of #514 and #515

**Comment by 585381** [comment]
Same as me. 
I have added the log file.

This is recent as was working perfect 14 hours ago.

[Spotify log 028e0e545b3e.txt](https://github.com/user-attachments/files/16309707/Spotify.log.028e0e545b3e.txt)

**Comment by jmlt** [comment]
Same here.

Amoled version was working fine couple hours ago but now is crashing. 
Updated xmanager through github successfully. 
Download new versions returns file not found.

Sams s22

**Comment by sappyblaze** [comment]
same for me, I use a galaxy a03

**Comment by MrBurgerCZ** [comment]
Now it doesn't even show versions, just N/A

**Comment by Remonell** [comment]
Same for me. Nothing Phone 2

**Comment by nocciol4** [comment]
Me too. 
- xiaomi 14

**Comment by MrBurgerCZ** [comment]
Spotify works now...

**Comment by 585381** [comment]
Yep, working here as well
Maybe issue was Spotify?

**Comment by Prosacwar** [comment]
> Clone of #514 and #515

Well I mean if everyone is having the issue obviously they're gonna talk about it -_-

**Comment by xC3FFF0E** [comment]
Up and running again. Closing.

**Comment by M2539-tech** [comment]
I had the same problem. I uninstalled both Spotify and xManager apps and when I read here that the bug was fixed I re-installed everything. 
However, now if I try to log back into Spotify, I get a window saying “An error has occurred. Please try again.”
Is this always a temporary bug? Or what can I do if the problem persists?

**Comment by 585381** [comment]
> > Clone of #514 and #515
> 
> Well I mean if everyone is having the issue obviously they're gonna talk about it -_-

Thanks for your insight legend

**Comment by remznwf** [comment]
So happy its back up and running.
