### ISSUE TITLE
Spotify is crashing 

### ISSUE THREAD

**Issue by Edilrob** [Team-xManager/xManager#519]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  s22
- Android Version:  android 14
- ROM Version:  stock
- xManager Version:  5.6
```

### 📝 Description

1. When opened 
2.spotify crashes 
3.then when I try to download newer versions 
After seeing the ads the website shows nothing 
...

**Comment by NojusKojos** [comment]
same for me (im using a s20 ultra 5g)

btw to not see the ads you can use a private dns. I personally use dns.adguard.com

**Comment by xC3FFF0E** [comment]
Up and running again. Closing.

**Comment by Edilrob** [comment]
Thanks guys it is running again without any problems for now
