### ISSUE TITLE
Still cant download after it's fixed

### ISSUE THREAD

**Issue by Chiasaa** [Team-xManager/xManager#520]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung S20 FE
- Android Version:  13
- ROM Version:  what's ROM Version?
- xManager Version:  5.6
```

### 📝 Description

1. After i choose which to download, it's shows ads and everything fine
2. After the ads, when there's download button
3. Suddenly this pop-up appears
...

### 📸 Screenshots

![Screenshot_20240719_233649_Package installer](https://github.com/user-attachments/assets/70d0b320-8d4b-497a-9459-62c9bdaa34ed)

**Comment by Chiasaa** [comment]
This what the file looks like

![Screenshot_20240719_234608_My Files](https://github.com/user-attachments/assets/e3820791-2ca7-4fde-846f-d8fb81ff9120)

**Comment by BrownyEz** [comment]
same here

**Comment by xC3FFF0E** [comment]
https://github.com/Team-xManager/xManager/issues/522#issuecomment-2240820420

Try this.

**Comment by Chiasaa** [comment]
> [#522 (comment)](https://github.com/Team-xManager/xManager/issues/522#issuecomment-2240180018)
> 
> Try this.

Tried, but still didnt work, even after i reinstall the xmanager, tried it again, still keeps showing "there was a problem parsing the package"

**Comment by Chiasaa** [comment]
> [#522 (comment)](https://github.com/Team-xManager/xManager/issues/522#issuecomment-2240180018)
> 
> Try this.

Also, i tried downloading the clone, or the experimental, it's still the same, i tried downloading the older release, itxs also the same "there was a problem parsing the package" so.. it's not only error for the latest release, also for other versions

**Comment by car011522** [comment]
hey i just downloaded this like an hour ago and i've been facing the same trouble as you, i tried using mirror link and it kinda worked? i'm using an alt spotify account cause my main account's premium expires soon but i still have it for the next few days so i won't know until then.

**Comment by Chiasaa** [comment]
> hey i just downloaded this like an hour ago and i've been facing the same trouble as you, i tried using mirror link and it kinda worked? i'm using an alt spotify account cause my main account's premium expires soon but i still have it for the next few days so i won't know until then.

Thanks for the info, i'll try

**Comment by Chiasaa** [comment]
> hey i just downloaded this like an hour ago and i've been facing the same trouble as you, i tried using mirror link and it kinda worked? i'm using an alt spotify account cause my main account's premium expires soon but i still have it for the next few days so i won't know until then.

It does work, thanks! Also.. if developer seen this, you can closs this, if anyone see this, try mirror link, it does work for me, hope also does work for anyone.

**Comment by car011522** [comment]
That's great! Thanks for trying it out for me, enjoy the free spotify lol
