### ISSUE TITLE
Playback queue not working

### ISSUE THREAD

**Issue by kunsh13** [Team-xManager/xManager#523]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [x] I did a clean install of xManager

### ℹ Information

```markdown
- Android Version:  14
- ROM Version:  stock
- Spotify Version: 8.9.56.618  (Exprimental)
- xManager Version:  5.6
- Device Model Samsung S21 Fe
```

### 📝 Description

- when clicking on three dots on a song and clicking add queue in spotify
- Error pops: unable to add this content to the queue

**Comment by sxc2582** [comment]
S24u Same issue

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
