### ISSUE TITLE
Features of spicetify / Themes and custom home page

### ISSUE THREAD

**Issue by tom-321** [Team-xManager/xManager#524]
### Description of the new feature / enhancement

- 1 Themes
- 2 custom home page
- 3 Lyrics ?

I don't know how Spotify light app was programmed, 
but I guess if it's possible to create a compled custom app, 
it may be possible to implement those three modifications
https://spicetify.app/

**Comment by owosoup** [comment]
Spicetify is for desktop. AFAIK Xmanager is for mobile.

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport

**Comment by tom-321** [comment]
> Spicetify is for desktop. AFAIK Xmanager is for mobile.
This should be just an example for features, I thought that maybe those features could be implemented in xManager...
