### ISSUE TITLE
spotify on wear os

### ISSUE THREAD

**Issue by crazyriz** [Team-xManager/xManager#528]
### Description of the new feature / enhancement

Hi, Is there a way to patched a spotify wear os ver? I go jogging without phone, but only have modded spotify on phone not on wearable devices.

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport

**Comment by DARKSiDEOFTHEWORLD2316** [comment]
💩💩Poop💩💩
