### ISSUE TITLE
Playback Bug 

### ISSUE THREAD

**Issue by aguilero** [Team-xManager/xManager#530]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  OnePlus 12
- Android Version:  14
- ROM Version:  stock 
- xManager Version:  5.6
```

### 📝 Description

1.When clicking the previous, next, or pause buttons, playback stops.
2.After entering the app, if you click the currently playing song again, it won't play.
3.You need to force stop the app and reopen it to play normally.
4.This issue occurs about every 10 minutes.
...

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
