### ISSUE TITLE
Favorites are still forced random

### ISSUE THREAD

**Issue by owosoup** [Team-xManager/xManager#532]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: realme 9 (non 5G) 
- Android Version:  13
- ROM Version:  stock
- xManager Version:  5.6
```

### 📝 Description

1. Play songs from the favourites playlist
2. Try to disable the shuffled playback
3. You can't.
4. You can on other playlists
...

### 📸 Screenshots

![Screenshot_2024-08-12-00-56-06-76_305a1a3985c21ffed1ac8d6efbd1fa75](https://github.com/user-attachments/assets/0b39f67c-7aad-4461-88aa-5481783dbc63)

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
