### ISSUE TITLE
Bring back smart shuffle

### ISSUE THREAD

**Issue by HackZy01** [Team-xManager/xManager#537]
### Description of the new feature / enhancement

"Shuffle and get recommendations in your Queue"

It's been removed in 8.9.18.512

It's nice to have this feature, because it lets you try something new with a similar feel to your playlist

### 📸 Screenshots

![Screenshot_20240824-200028](https://github.com/user-attachments/assets/8e18146d-eeb3-4d98-9247-3fef9ae40cf8)

**Comment by nazial-k** [comment]
One of the better features. Hope they bring it back.

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
