### ISSUE TITLE
Fix the widget on android

### ISSUE THREAD

**Issue by HiroTheOne** [Team-xManager/xManager#538]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung S20 Fe 5G
- Android Version:  Android 13
- ROM Version:  stock
- xManager Version:  5.6
```

### 📝 Description

1. The widget used to show on the bottom the last playlist or song you listened to and now it doesnt show anymore.
2. On the left there used to be a picture of the current song being listened but it doesnt show it anymore.
I really liked this feature, it was pretty cool so I hope it can be fixed.

### 📸 Screenshots

![Screenshot_20240824_232922_Nova Launcher](https://github.com/user-attachments/assets/139fbcc7-df0a-459e-a1d4-377fca7f62e5)

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
