### ISSUE TITLE
ANy way to download music (not cache way)

### ISSUE THREAD

**Issue by HakaishinShwet** [Team-xManager/xManager#542]
Maybe with yt-dlp program spotify playlist songs can be searched and downloaded on user request at 320 kbps ?

**Comment by xC3FFF0E** [comment]
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport
