### ISSUE TITLE
Getting the lyrics back

### ISSUE THREAD

**Issue by NULLandONE** [Team-xManager/xManager#550]
### Description of the new feature / enhancement

So, the problem:
Spotify recently disabled the lyrics on mobile and now they can't see the lyrics
The solution:
I noticed that the web version of Spotify has still lyrics (open https://open.spotify.com on PC, and click on a song, and press on lyrics), so if we take the functionality from the web version, and patch the app so that it uses the website API instead of the old one, how would that sound?

**Comment by xC3FFF0E** [comment]
Already added on the latest version. Closing.

**Comment by soliviantar** [comment]
> Already added on the latest version. Closing.


For some reason it is not working for me. I see "![Screenshot_20241001-093605_Spotify.png](https://github.com/user-attachments/assets/c095073f-047f-44c2-b72f-68dafe367a62)Lyrics" but there are no lyrics. If I tap on it a ![Screenshot_20241001-093613_Spotify.png](https://github.com/user-attachments/assets/c60952e5-9f6e-4d33-81d3-9d7abfd684b1)transparent screen comes up.
